// Author: Jiannan Tian

#ifndef ARGUMENT_PARSER_DOCUMENT_HH
#define ARGUMENT_PARSER_DOCUMENT_HH

#include <regex>
#include <string>

const std::string fmt_b("\e[1m");
const std::string fmt_0("\e[0m");

const std::regex  bful("@(.*?)@");
const std::string bful_text("\e[1m\e[4m$1\e[0m");
const std::regex  bf("\\*(.*?)\\*");
const std::string bf_text("\e[1m$1\e[0m");
const std::regex  ul(R"(_((\w|-|\d|\.)+?)_)");
const std::string ul_text("\e[4m$1\e[0m");
const std::regex  red(R"(\^\^(.*?)\^\^)");
const std::string red_text("\e[31m$1\e[0m");

std::string  //
Format(const std::string& s)
{
  auto a = std::regex_replace(s, bful, bful_text);
  auto b = std::regex_replace(a, bf, bf_text);
  auto c = std::regex_replace(b, ul, ul_text);
  auto d = std::regex_replace(c, red, red_text);
  return d;
}

static const char psz_short_doc[] =
    "\n"
    "usage: cusz zip [-i file] [-t dtype] [-m mode] [-e eb] [-l x-y-z] \n"
    "       cusz unzip [-i file] [--compare ori-file] \n"
    // "            (OPTIONAL) [-p p1,c1[,c2]] [-a tuning]"
    // "...\n"
    // "  (or the -z/-x flag form: cusz [-zxh] [-i file] ...)\n"
    "\n"
    "  z : compress (or subcommand: _zip_)\n"
    "  x : decompress (or subcommand: _unzip_)\n"
    "  h : print full help document\n"
    "\n"
    "  i file   : path to input data\n"
    "  t dtype  : _f32_ (f64 to be updated)\n"
    "  m mode   : _abs_, _rel_/_r2r_\n"
    "  e eb     : error bound\n"
    "  l size   : _-l [x[-y[-z]]] (1,2,3-D)\n"
    "  p stages : the pipeline: p1,c1[,c2], e.g. \"lrz,hf\", \"spl-y25,hf,lc-rtr\";\n"
    "        trailing \"..\" defaults the rest, e.g. \"lrz..\", \"spl..\"\n"
    // "  --preset NAME : whole pipeline, no -p: \"fzg\", \"hicr\", \"hitp\", \"hitp_r1\"\n"
    // "  --pipeline p1,c1[,c2] : whole pipeline by stage, e.g. \"spl-y25,hf,lc-rtr\";\n"
    // "        one stage may be \"_\" (also *, default), e.g. \"_,hfr-v2\";\n"
    // "        --pipeline preset:NAME names a whole pipeline\n"
    // "  a NAME  : auto tuning mode: \"CR-first\", \"RD-first\""
    "\n"
    "  report list: \n"
    "    syntax: opt[=v], \"kw1[=(on|off)],kw2[=(on|off)]\n"
    "    keywords: _quality_, _cr_\n"
    "    example: \"--report quality\", \"--report quality=off\"\n"
    "\n"
    "example:\n"
    "   cusz zip -t f32 -m rel -e 1e-4 -i ${CESM} -l 3600-1800 --report cr\n"
    "   cusz unzip -i ${CESM}.cusza --report quality --compare ${CESM}\n"
    "\n"
    "\"cusz -h\" for details.\n";

static const char psz_full_doc[] =
    // clang-format off
    "*NAME*\n"
    "    cuSZ: A GPU-accelerated error-bounded lossy compressor for scientific data\n\n"
    "*SYNOPSIS*\n"
    "    *cusz*  <command>\n"
    "    *cusz*  [options]\n\n"
    "    *cusz* *zip* *-t* f32 *-m* [eb mode] *-e* [eb] *-i* [filename] *-l* [x[-y[-z]]]\n"
    "    *cusz* *unzip* *-i* [filename].cusza\n"
    "\n"
    "*COMMANDS*\n"
    "    *zip*     : compress data (also *compress*, *comp*)\n"
    "    *unzip*   : decompress data archive (also *decompress*, *decomp*)\n"
    "\n"
    "*SAMPLES*\n"
    "    *cusz*  *zip*  *-t* f32  *-m* rel  *-e* 1.0e-4.0  *-i* ${HURR}  *-l* 500-500-100 *--report* cr\n"
    "    ^^           (type)  (mode)  (err bound)  (input)     (x-y-z order)^^\n"
    "\n"
    "    *cusz*  *unzip*  *-i* ${CESM}  *--compare* ${HURR}\n"
    "    ^^             (archive)   (original data)^^\n"
    "\n"
    "*OPTIONS*\n"
    "  ^^*mandatory::zip*^^\n"
    "    *cusz* *zip* ... (recommended); alternatively, *-z*, *--compress*, or *--*@z@*ip*\n"
    "\n"
    "    *-m* or *--*@m@*ode* <abs|r2r>  Specify compression mode.\n"
    "        _abs_: absolute mode\n"
    "        _rel_/_r2r_: relative to value-range, = eb * value-range\n"
    "\n"
    "    *-e*, *--eb*, or *--error-bound* [num]\n"
    "        Specify error bound. e.g., _1.23_, _1e-4_, _1.23e-4.56_\n"
    "\n"
    "    *-i* or *--*@i@*nput* [file]\n"
    "\n"
    // "    *-d* or *--dict-size* [256|512|1024|...]\n"
    // "        Specify a power-of-2 dictionary size/quantization bin number.\n"
    // "\n"
    "    *-l* [x[-y[-z]]]  Specify (1|2|3)D (fast-to-slow) data dimension.\n"
    "        A delimiters can be \'x\', \'*\', \'-\', \',\' or \'m\'.\n"
    "\n"
    "  ^^*mandatory::unzip*^^\n"
    "    *cusz* *decompress* ... (recommended); alternatively, *-x*, *--e*@x@*tract*, *--decompress*, or *--unzip*\n"
    "\n"
    "    *-i* or *--*@i@*nput* [compressed file]\n"
    "\n"
    "  ^^*alternative::command*^^\n"
    "    *--math-order*, *--zyx*, or *--slowest-to-fastest*  Math dimension "
    "order.\n"
    "\n"
    "    *-l*, *--len*, *--xyz*, or *--dim3*  CUDA dimension order.\n"
    "\n"
    "  ^^*optional::assessment*^^\n"
    "    *--compare* /path/to/origin-data\n"
    "        Evaluate data quality and print a report.\n"
    "\n"
    "  ^^*optional::composition*^^\n"
    "    *-p* or *--pipeline* p1,c1[,c2], with \"..\" defaults the rest.\n"
    "        e.g. \"lrz..\"; or \"preset:NAME\".\n"
    "        + predictors: \n"
    "            _lrz_ or _lorenzo_ (default), _lrz-zz_ (zigzag),\n"
    "            _spl_, _spline_ or _spl-y25_ (2D+3D, SC '25), _spl-y24_ (3D only, SC '24)\n"
    "        + codecs for _c1_: \n"
    "            _hfr-pbkc_ (default),\n"
    "            _hf_ (legacy), _hfr-v2_, _hfr-v4_ (experimental, IPDPS '21),\n"
    "            _hfr-pbkgo_ (experimental),\n"
    "            _fzg_ (legacy, HPDC '23; takes _lrz-zz_, not _lrz_), \n"
    "            _lc-drh_, _lc-tcms_ (LC path, SC '25)\n"
    "        + codecs for _c2_ only: \n"
    "            _lc-bitr_, _lc-rtr_ (LC path, SC '25); _lc-tcms_ also fits here\n"
    "        the _hfr-*_ codecs take _lrz_ or _spl*_, not _lrz-zz_.\n"
    "\n"
    // "    *--preset* NAME\n"
    // "        A whole pipeline by name, no *-p* needed: \"fzg\", \"hicr\", "
    // "\"hitp\", \"hitp_r1\"\n"
    // "\n"
    // "    *--hist* or *--histogram* <generic|sparse>\n"
    // "        Select from the following histogramming method: \n"
    // "        + _generic_: (default) for all quant-code distributions.\n"
    // "        + _sparse_: may outperform _generic_ in high-ratio cases.\n"
    // "\n"
    "  ^^*optional::report::stdout*^^\n"
    "    *--report* (option=on/off)-list\n"
    "        syntax: opt[=v], \"kw1[=(on|off)],kw2=[=(on|off)]\n"
    "        keywords: \'time\', \'cr\', \'quality\', \'compressibility\'\n"
    "        example: \"--report time,cr\", \"--report time=off\"\n"
    "\n"
    "  ^^*optional::dump-internal-buffer*^^\n"
    "    *--dump* <quant|hist>\n"
    "        _quant_ : quant-code binary ^^\"[fname].[mode]_[eb].qt_<u1|u2>\"^^\n"
    "        _hist_  : histogram binary ^^\"[fname].[mode]_[eb].ht[r*2]_u4\"^^\n"
    "\n"
    "  ^^*help::doc*^^\n"
    "    *-h* or *--help*  Query documentation.\n"
    "\n"
    "    *-v* or *--version*  Query build number.\n"
    "\n"
    "    *-V* or *--versioninfo* or *--query-env*  Query runtime.\n"
    "\n"
    "*EXAMPLES*\n"
    "  ^^*compression pipelines*^^\n"
    "    -p lrz..         : Lorenzo + default encoder (balanced)\n"
    "    -p spl,hf        : Spline-3D + Huffman coding (high-quality)\n"
    "    -p 'preset:fzg'  : revised Lorenzo + FZGPU-coding (HPDC '23)\n"
    "    -p 'preset:hicr' : (with caveats) Spline-3D + HiCR config (SC '25)\n"
    "    -p 'preset:hitp' : (with caveats) Spline-3D + HiTP config (SC '25)\n"
    "\n"
    "  ^^*testing data*^^\n"
    "    Get testing data from Scientific Data Reduction Benchmarks (SDRB)\n"
    "    at https://sdrbench.github.io\n"
    "\n"
    "    # 2D *CESM* example (compression and decompression):\n"
    "    cusz zip -t f32 -m rel -e 1e-4 -i ${CESM} -l 3600-1800 "
    "--report time\n"
    "    cusz unzip -i ${CESM}.cusza --report time --compare "
    "${CESM}\n"
    "\n"
    "    # 3D *Hurricane Isabel* example (compression and decompression):\n"
    "    cusz zip -t f32 -m rel -e 1e-4 -i ${HURR} -l 500-500-100\n"
    "    cusz unzip -i ${HURR}.cusza\n";

static const char huff_re_short_doc[] =
    "\n"
    "OVERVIEW: Huffman submodule as standalone program\n"  // TODO from this
                                                           // line on
    "\n"
    "USAGE:\n"
    "  The basic use with demo data is listed below,\n"
    "    ./huff --encode --decode --verify --input ./baryon_density.dat.b16 "
    "\\\n"
    "        -3 512 512 512 --input-rep 16 --huffman-rep 32 --huffman-chunk "
    "2048 --dict-size 1024\n"
    "  or shorter\n"
    "    ./huff -e -d -V -i ./baryon_density.dat.b16 -3 512 512 512 -R 16 -H "
    "32 -C 2048 -c 1024\n"
    "            ^  ^  ^ --------------------------- -------------- ----- "
    "----- ------- -------\n"
    "            |  |  |       input data file         dimension   input "
    "Huff. Huff.   codebook\n"
    "          enc dec verify                                       rep.  "
    "rep.  chunk   size\n"
    "\n"
    "EXAMPLES\n"
    "  Essential:\n"
    "    ./bin/huff -e -d -i ./baryon_density.dat.b16 -3 512 512 512 -R 16 -c "
    "1024\n"
    "    have to input dimension, and higher dimension for a multiplication "
    "of each dim.,\n"
    "    as default values input-rep=16 (bits), huff-rep=32 (bits), "
    "codebook-size=1024 (symbols)\n"
    "\n";

static const char doc_dim_order[] =
    "\n"
    "  Input dimension follows low-to-high (e.g., x-y-z) order.\n"
    "  Taking 2D CESM-ATM as an example, \n"
    "\n"
    "  |<------------------------- x 3600 --------------------------->|    \n"
    "  +--------------------------------------------------------------+  - \n"
    "  |                                                              |  ^ \n"
    "  |                                                              |  | \n"
    "  |              CESM-ATM:    1800x3600 (y-x order)              |  | \n"
    "  |              data name:  <field>_1800_3600                  |  y \n"
    "  |                                                              | 1800 "
    "\n"
    "  |              input:       -l 3600,1800                       |  | \n"
    "  |              input order: -l [x,y]                           |  | \n"
    "  |                                                              |  | \n"
    "  |                                                              |  v \n"
    "  +--------------------------------------------------------------+  - \n"
    "\n"
    "  Taking 3D Hurricane as another example, whose dimensions are\n"
    "  100x500x500, the input is \"-l 500,500,100\".\n";

#endif
