#include "histsp_compat.cuhip.inl"

SPECIALIZE_PSZCXX_COMPAT_MODULE_HIST_CAUCHY(CUDA, u1)
SPECIALIZE_PSZCXX_COMPAT_MODULE_HIST_CAUCHY(CUDA, u2)
SPECIALIZE_PSZCXX_COMPAT_MODULE_HIST_CAUCHY(CUDA, u4)
SPECIALIZE_PSZCXX_COMPAT_MODULE_HIST_CAUCHY(CUDA, f4)
