#include "detail/l23_c.cuhip.inl"

INSTANCIATE_GPU_L23R_1param(f4);
INSTANCIATE_GPU_L23R_1param(f8);

#undef INSTANCIATE_GPU_L23R_1param
#undef INSTANCIATE_GPU_L23R_2params
#undef INSTANCIATE_GPU_L23R_3params

INSTANCIATE_GPU_L23_PREQ_1param(f4);
INSTANCIATE_GPU_L23_PREQ_1param(f8);

#undef INSTANCIATE_GPU_L23_PREQ_1param
#undef INSTANCIATE_GPU_L23_PREQ_2params
#undef INSTANCIATE_GPU_L23_PREQ_3params