#include "detail/lproto_x.cuhip.inl"

INSTANTIATIE_LORENZO_PROTO_X_1param(f4);
INSTANTIATIE_LORENZO_PROTO_X_1param(f8);

#undef INSTANTIATIE_LORENZO_PROTO_X_1param
#undef INSTANTIATIE_LORENZO_PROTO_X_2params
