message("[psz::info] $\{CMAKE_VERSION\}: " ${CMAKE_VERSION})
message("[psz::info] $\{CMAKE_C_STANDARD\}$: " ${CMAKE_C_STANDARD})
message("[psz::info] $\{CMAKE_C_COMPILER\}$: " ${CMAKE_C_COMPILER})
message("[psz::info] $\{CMAKE_C_COMPILER_ID\}$: " ${CMAKE_C_COMPILER_ID})
message("[psz::info] $\{CMAKE_C_COMPILER_VERSION\}$: " ${CMAKE_C_COMPILER_VERSION})
message("[psz::info] $\{CMAKE_CXX_STANDARD\}$: " ${CMAKE_CXX_STANDARD})
message("[psz::info] $\{CMAKE_CXX_COMPILER\}$: " ${CMAKE_CXX_COMPILER})
message("[psz::info] $\{CMAKE_CXX_COMPILER_ID\}$: " ${CMAKE_CXX_COMPILER_ID})
message("[psz::info] $\{CMAKE_CXX_COMPILER_VERSION\}$: " ${CMAKE_CXX_COMPILER_VERSION})

if(PSZ_BACKEND STREQUAL "CUDA" OR PSZ_BACKEND STREQUAL "cuda")
  message("[psz::info] $\{CMAKE_CUDA_STANDARD\}: " ${CMAKE_CUDA_STANDARD})
  message("[psz::info] $\{CMAKE_CUDA_COMPILER\}: " ${CMAKE_CUDA_COMPILER})
  message("[psz::info] $\{CMAKE_CUDA_COMPILER_ID\}: " ${CMAKE_CUDA_COMPILER_ID})
  message("[psz::info] $\{CMAKE_CUDA_COMPILER_VERSION\}: " ${CMAKE_CUDA_COMPILER_VERSION})
  message("[psz::info] $\{CMAKE_CUDA_ARCHITECTURES\}: " ${CMAKE_CUDA_ARCHITECTURES})
elseif(PSZ_BACKEND STREQUAL "HIP" OR PSZ_BACKEND STREQUAL "hip")
  message("[psz::info] $\{CMAKE_HIP_STANDARD\}: " ${CMAKE_HIP_STANDARD})
  message("[psz::info] $\{CMAKE_HIP_COMPILER\}: " ${CMAKE_HIP_COMPILER})
  message("[psz::info] $\{CMAKE_HIP_COMPILER_ID\}: " ${CMAKE_HIP_COMPILER_ID})
  message("[psz::info] $\{CMAKE_HIP_COMPILER_VERSION\}: " ${CMAKE_HIP_COMPILER_VERSION})
  message("[psz::info] $\{CMAKE_HIP_ARCHITECTURES\}: " ${CMAKE_HIP_ARCHITECTURES})
elseif(PSZ_BACKEND STREQUAL "ONEAPI" OR PSZ_BACKEND STREQUAL "oneapi" OR PSZ_BACKEND STREQUAL "1api")
else()
  message(FATAL_ERROR "Unsupported PSZ_BACKEND selected: ${PSZ_BACKEND}")
endif()

